version: "3.8"
services:
  # job-service:
  #   build: ./examen
  #   ports:
  #     - "8081:8081"
  #   hostname: job-service
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
  #   depends_on:
  #     - discovery-service
  #     - docker-mysql

  # docker-mysql:
  #   image: "mysql"
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=admin
  #     - MYSQL_DATABASE=admin
  #   ports:
  #     - "3306:3306"

  # candidat-service:
  #   image: "candidat-service"
  #   ports:
  #     - "8088:8088"
  #   build: ./candidat
  #   hostname: Candidat
  #   environment:
  #     - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
  #   depends_on:
  #     - discovery-service

  payment-management-service:
    image: "payment-management"
    ports:
      - "8088:8088"
    build: ./payment-management
    hostname: payment-management
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service

  Gateway-service:
    image: "gateway-service"
    ports:
      - "8089:8089"
    build: ./Gateway
    hostname: Gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
    depends_on:
      - discovery-service
      - payment-management-service
      # - job-service

  discovery-service:
    container_name: discovery-service
    build: ./Eureka_Server
    ports:
      - "8761:8761"
    hostname: discovery-service
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
